include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/common/**/*.chopper.dart
    - lib/common/**/*.freezed.dart
    - lib/common/**/*.g.dart

dart_code_metrics:
  anti-patterns:
    - long-method
  rules:
    # common
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 5
    - avoid-non-ascii-symbols
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-type-assertions
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-use-expanded-as-spacer
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-immediate-return
    - prefer-moving-to-variable
    - prefer-last
    - prefer-first

    # flutter
    - avoid-border-all
    - always-remove-listener
    - avoid-unnecessary-setstate
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - validator
        allowed-line-count: 3
    - prefer-const-border-radius
    - prefer-correct-type-name
    - avoid-returning-widgets

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    prefer_expression_function_bodies: true
    prefer_initializing_formals: true
    prefer_relative_imports: true
    public_member_api_docs: false
    always_use_package_imports: false
    library_private_types_in_public_api: false
    avoid_multiple_declarations_per_line: true
    eol_at_end_of_file: true
    noop_primitive_operations: true
    prefer_constructors_over_static_methods: true
    require_trailing_commas: true
    use_if_null_to_convert_nulls_to_bools: true
    avoid_final_parameters: true
    non_constant_identifier_names: true
    no_leading_underscores_for_local_identifiers: true
    unnecessary_to_list_in_spreads: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    discarded_futures: true
    no_duplicate_case_values: true
    combinators_ordering: true